# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  spark:
    image: docker.io/bitnami/spark:3.5.2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - .:/home/jovyan/workspace
      - ${PARQUET_PATH}:/home/jovyan/parquet
  spark-worker:
    image: docker.io/bitnami/spark:3.5.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_CORES=10
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - .:/home/jovyan/workspace
      - ${PARQUET_PATH}:/home/jovyan/parquet
  almond:
    image: almondsh/almond:latest
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=almond
    volumes:
      - .:/home/jovyan/workspace
      - ${PARQUET_PATH}:/home/jovyan/parquet